/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_management;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.BorderFactory;

/**
 *
 * @author CSE
 */
public class ex_registration extends javax.swing.JFrame {
    Connection conn;
    Statement stt;
    ResultSet res;

    /**
     * Creates new form ex_registration
     */
    public ex_registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        e_id = new javax.swing.JTextField();
        e_date = new javax.swing.JTextField();
        e_nid = new javax.swing.JTextField();
        nation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        e_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        e_des = new javax.swing.JTextField();
        e_name = new javax.swing.JTextField();
        e_number = new javax.swing.JTextField();
        e_dob = new javax.swing.JTextField();
        e_add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 24)); // NOI18N
        jLabel2.setText("Officer Registration");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setText("ID :");

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel11.setText("Join Date :");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel6.setText("NID :");

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel10.setText("Nationality :");

        e_id.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_idActionPerformed(evt);
            }
        });

        e_date.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_dateActionPerformed(evt);
            }
        });

        e_nid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_nidActionPerformed(evt);
            }
        });

        nation.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setText("Password :");

        e_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e_id, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(e_nid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e_date)
                    .addComponent(e_pass))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(e_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(e_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(e_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(e_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel5.setText("Phone number :");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth :");

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel9.setText("Address :");

        e_des.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_desActionPerformed(evt);
            }
        });

        e_name.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_nameActionPerformed(evt);
            }
        });

        e_number.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_numberActionPerformed(evt);
            }
        });

        e_dob.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_dobActionPerformed(evt);
            }
        });

        e_add.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        e_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_addActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel12.setText("Designation :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(e_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(e_number)
                        .addComponent(e_des)
                        .addComponent(e_name)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(e_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_idActionPerformed

    private void e_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_dateActionPerformed

    private void e_nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_nidActionPerformed

    private void nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationActionPerformed

    private void e_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_desActionPerformed

    private void e_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_nameActionPerformed

    private void e_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_numberActionPerformed

    private void e_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_dobActionPerformed

    private void e_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_addActionPerformed

    public int ex_validation_empty(String id, String name1,String pass,String join_date,String nation1,String nid,String designation,String p_number,String dob,String address){
        String errorset= "";
        int check=0;
        
        //id
            if(id == null || id.isEmpty()){
                e_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Id should not be empty!\n";
                check=1;
            }
            else if(id.matches("^[A-Z|a-z].*[0-9]$")){
                if(id.length()>11){
                    errorset+="Id should be Less than 11 degits.\n";
                    check=1;
                }
                else{
                    e_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
            }
            else if(!id.matches("^[A-Z|a-z].*[0-9]$")){
                e_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid ID\n";
                check=1;
            }

                //pass
            if(pass == null || pass.isEmpty()){
                errorset+="Password should not be empty!\n";
                e_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if(pass.length()<6){
                errorset+="Password length should be more than or equal 6!\n";
                 e_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else{
                e_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
           
            
            //join date
            if(join_date == null || join_date.isEmpty()){
                e_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="join_date should not be empty! format (yyyy-mm-day)\n";
                check=1;
            }
            
            else if (!join_date.matches("^(\\d{4})-(\\d{1,2})-(\\d{1,2})$")) {
                e_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid join date! format (yyyy-mm-day)\n";
                check=1;
            }
            else{
                 e_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //country
            if(nation1 == null || nation1.isEmpty()){
                errorset+="Nation should not be empty!\n";
                nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if (!nation1.matches("^[A-z]+$")) {
                nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Nation is invalid!";
                check=1;
            }
            else{
                 nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //nid
            if(nid == null || nid.isEmpty()){
                e_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="NID  should not be empty!\n";
                check=1;
            }
            
            else if(!nid.matches("^[0-9]*$")){
                e_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid NID\n";
                check=1;
            }
            else{
                e_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            if(designation == null || designation.isEmpty()){
                e_des.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Designation should not be empty!\n";
                check=1;
            }
            else if (!designation.matches("^[A-z]+$")) {
                e_des.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Designation is invalid!";
                check=1;
            }
            else{
                 e_des.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            
            //name
            if(name1 == null || name1.isEmpty()){
                e_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Name should not be empty!\n";
                check=1;
            }
            else if (name1.matches("^[a-zA-Z\\s]+$")) {
                if(name1.length()<4){
                    e_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                    errorset+="Name should be grater than 3 letter!";
                    check=1;
                }
                else{
                    e_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
              
            }
            else if(!name1.matches("^[a-zA-Z\\s]+$")){
                 e_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Name is  invalid!";
                 check=1;
            }
           
            
            //phone number
            if(p_number == null || p_number.isEmpty()){
                errorset+="Phone Number should not be empty!\n";
                e_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
             else if(!p_number.matches("^(?:\\+88|01)?\\d{11}$")){
                 e_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Phone Number is not valid!\n";
                 check=1;
            }
             else{
                 e_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
             }
            
            //dob
            if(dob == null || dob.isEmpty()){
                errorset+="Date of Birth should not be empty! format (yyyy-mm-day)\n";
                e_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if (!dob.matches("^(\\d{4})-(\\d{1,2})-(\\d{1,2})$")) {
                e_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid Date of Birth ! format (yyyy-mm-day)\n";
                check=1;
            }
            else{
                 e_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //address
            if(address == null || address.isEmpty()){
                e_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Address should not be empty!\n";
                check=1;
            }
            else if (address.matches("^[a-zA-Z\\s]+$")) {
                if(address.length()<4){
                    e_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                    errorset+="Address should be grater than 3 letter!\n";
                    check=1;
                }
                else{
                    e_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
              
            }
            else if(!address.matches("^[a-zA-Z\\s]+$")){
                 e_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Address is  invalid!\n";
                 check=1;
            }
            
            
            if(check==0)
                return 0;
            else{
                JOptionPane.showMessageDialog(null,errorset);
                return 1;
            }
                    
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
                conn = Dbconnect.dbconnection();
                stt = conn.createStatement();
                stt.execute("USE bank_management");
                
                String id=e_id.getText();
                String name1=e_name.getText();
                String pass= e_pass.getText();
                String join_date=e_date.getText();
                String nation1 =nation.getText();
                String nid=e_nid.getText();
                String designation=e_des.getText();
                String p_number=e_number.getText();
                String dob=e_dob.getText();
                String address=e_add.getText();
                
                int check=1;
                check = ex_validation_empty(id,name1,pass,join_date,nation1,nid,designation,p_number,dob,address);
                
                
                if(check==0){
                    String query="INSERT INTO  executive(id,pass,join_date,nation,nid,designation,name,p_number,dob,address) VALUES('"+e_id.getText()+"','"+e_pass.getText()+"',"
                        + "'"+e_date.getText()+"','"+nation.getText()+"','"+e_nid.getText()+"','"+e_des.getText()+"','"+e_name.getText()+"','"+e_number.getText()+"','"+e_dob.getText()+"','"+e_add.getText()+"')";

                     stt.execute(query);
                     JOptionPane.showMessageDialog(null,"Successfully Inserted !");
                     e_id.setText("");
                     e_name.setText("");
                     e_date.setText("");
                     nation.setText("");
                     e_nid.setText("");
                     e_des.setText("");
                     e_pass.setText("");
                     e_add.setText("");
                     e_dob.setText("");
                     e_number.setText("");
                }

            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Id is alreay Exist");
                e_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));// sarver error ,show message
            }
         
         //finally close the connection
         finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (stt != null) {
                    stt.close();
                }
            } catch (SQLException sqlee) {
                JOptionPane.showMessageDialog(null,"Id is already Exist");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        e_id.setText(""); e_pass.setText(""); e_date.setText(""); nation.setText(""); e_nid.setText(""); e_des.setText(""); 
        e_name.setText(""); e_number.setText(""); e_dob.setText(""); e_add.setText(""); 
       
        e_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_des.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        e_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_add;
    private javax.swing.JTextField e_date;
    private javax.swing.JTextField e_des;
    private javax.swing.JTextField e_dob;
    private javax.swing.JTextField e_id;
    private javax.swing.JTextField e_name;
    private javax.swing.JTextField e_nid;
    private javax.swing.JTextField e_number;
    private javax.swing.JPasswordField e_pass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nation;
    // End of variables declaration//GEN-END:variables
}
