package bank_management;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

public class user_registration extends javax.swing.JFrame {
    Connection conn =null;
    Statement stt;
    ResultSet res;
    /**
     * Creates new form NewJFrame
     */
    public user_registration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        u_date = new javax.swing.JTextField();
        a_type = new javax.swing.JTextField();
        nation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        u_pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        u_name = new javax.swing.JTextField();
        u_number = new javax.swing.JTextField();
        u_dob = new javax.swing.JTextField();
        u_add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        u_nid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 24)); // NOI18N
        jLabel2.setText("CUSTOMER REGISTRATION");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setText("Account ID :");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setText("Password :");

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel11.setText("Join Date :");

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel10.setText("Nationality");

        u_id.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });

        u_date.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_dateActionPerformed(evt);
            }
        });

        a_type.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        a_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_typeActionPerformed(evt);
            }
        });

        nation.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel13.setText("Account Type :");

        u_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_date, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a_type))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_id, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(u_pass))
                        .addContainerGap(16, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel4.setText("NID :");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel5.setText("Phone number :");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth :");

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel9.setText("Address :");

        u_name.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_nameActionPerformed(evt);
            }
        });

        u_number.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_numberActionPerformed(evt);
            }
        });

        u_dob.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_dobActionPerformed(evt);
            }
        });

        u_add.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_addActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel12.setText("Name :");

        u_nid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        u_nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_nidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(u_add, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(u_number, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_nid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(u_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(u_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(u_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jButton1)
                                .addGap(45, 45, 45)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void a_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_typeActionPerformed

    private void nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationActionPerformed

    private void u_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_nameActionPerformed

    private void u_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_numberActionPerformed

    private void u_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_dobActionPerformed

    private void u_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_addActionPerformed

    private void u_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_dateActionPerformed

    private void u_nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_nidActionPerformed

    public int ex_validation_empty(String id, String name1,String pass,String join_date,String nation1,String nid,String a_type1,String p_number,String dob,String address){
        String errorset= "";
        int check=0;
        
        //id
            if(id == null || id.isEmpty()){
                u_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Id should not be empty!\n";
                check=1;
            }
            else if(id.matches("^[0-9]+$")){
                if(id.length()>11){
                    errorset+="Id should be Less than 11 degits.\n";
                    check=1;
                }
                else{
                    u_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
            }
            else if(!id.matches("^[0-9]+$")){
                u_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid ID\n";
                check=1;
            }

                //pass
            if(pass == null || pass.isEmpty()){
                errorset+="Password should not be empty!\n";
                u_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if(pass.length()<6){
                errorset+="Password length should be more than or equal 6!\n";
                 u_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else{
                u_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
           
            
            //join date
            if(join_date == null || join_date.isEmpty()){
                u_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="join_date should not be empty! format (yyyy-mm-day)\n";
                check=1;
            }
            
            else if (!join_date.matches("^(\\d{4})-(\\d{1,2})-(\\d{1,2})$")) {
                u_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid join date! format (yyyy-mm-day)\n";
                check=1;
            }
            else{
                 u_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //country
            if(nation1 == null || nation1.isEmpty()){
                errorset+="Nation should not be empty!\n";
                nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if (!nation1.matches("^[A-z]+$")) {
                nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Nation is invalid!";
                check=1;
            }
            else{
                 nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //nid
            if(nid == null || nid.isEmpty()){
                u_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="NID  should not be empty!\n";
                check=1;
            }
            
            else if(!nid.matches("^[0-9]*$")){
                u_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid NID\n";
                check=1;
            }
            else{
                u_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            if(a_type1 == null || a_type1.isEmpty()){
                a_type.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Account type should not be empty!\n";
                check=1;
            }
            else if (!a_type1.matches("^[A-z]+$")) {
                a_type.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Account type is invalid!";
                check=1;
            }
            else{
                 a_type.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            
            //name
            if(name1 == null || name1.isEmpty()){
                u_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Name should not be empty!\n";
                check=1;
            }
            else if (name1.matches("^[a-zA-Z\\s]+$")) {
                if(name1.length()<4){
                    u_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                    errorset+="Name should be grater than 3 letter!";
                    check=1;
                }
                else{
                    u_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
              
            }
            else if(!name1.matches("^[a-zA-Z\\s]+$")){
                 u_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Name is  invalid!";
                 check=1;
            }
           
            
            //phone number
            if(p_number == null || p_number.isEmpty()){
                errorset+="Phone Number should not be empty!\n";
                u_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
             else if(!p_number.matches("^(?:\\+88|01)?\\d{11}$")){
                 u_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Phone Number is not valid!\n";
                 check=1;
            }
             else{
                 u_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
             }
            
            //dob
            if(dob == null || dob.isEmpty()){
                errorset+="Date of Birth should not be empty! format (yyyy-mm-day)\n";
                u_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                check=1;
            }
            else if (!dob.matches("^(\\d{4})-(\\d{1,2})-(\\d{1,2})$")) {
                u_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Invalid Date of Birth ! format (yyyy-mm-day)\n";
                check=1;
            }
            else{
                 u_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
            }
            
            //address
            if(address == null || address.isEmpty()){
                u_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                errorset+="Address should not be empty!\n";
                check=1;
            }
            else if (address.matches("^[a-zA-Z\\s]+$")) {
                if(address.length()<4){
                    u_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                    errorset+="Address should be grater than 3 letter!\n";
                    check=1;
                }
                else{
                    u_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));
                }
              
            }
            else if(!address.matches("^[a-zA-Z\\s]+$")){
                 u_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
                 errorset+="Address is  invalid!\n";
                 check=1;
            }
            
            
            if(check==0)
                return 0;
            else{
                JOptionPane.showMessageDialog(null,errorset);
                return 1;
            }
                    
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
                conn = Dbconnect.dbconnection();
                stt = conn.createStatement();
                stt.execute("USE bank_management");
                
                 
                String id=u_id.getText();
                String name1=u_name.getText();
                String pass= u_pass.getText();
                String join_date=u_date.getText();
                String nation1 =nation.getText();
                String nid=u_nid.getText();
                String a_type1 =a_type.getText();
                String p_number=u_number.getText();
                String dob=u_dob.getText();
                String address=u_add.getText();
                
                int check=1;
                check = ex_validation_empty(id,name1,pass,join_date,nation1,nid,a_type1,p_number,dob,address);
               
                if(check==0){
                
                    String query="INSERT INTO user(id,pass,ac_type,join_date,nation,nid,name,p_number,dob,address) VALUES('"+u_id.getText()+"','"+u_pass.getText()+"',"
                        + "'"+a_type.getText()+"','"+u_date.getText()+"','"+nation.getText()+"','"+u_nid.getText()+"','"+u_name.getText()+"','"+u_number.getText()+"','"+u_dob.getText()+"','"+u_add.getText()+"')";

                     stt.execute(query);
                     JOptionPane.showMessageDialog(null,"Successfully Inserted !");

                     query="INSERT INTO  money(id,name,amount) VALUES('"+u_id.getText()+"','"+u_name.getText()+"','0')";
                     stt.execute(query);
                     u_id.setText("");
                     u_name.setText("");
                     u_date.setText("");
                     nation.setText("");
                     u_nid.setText("");
                     a_type.setText("");
                     u_pass.setText("");
                     u_add.setText("");
                     u_dob.setText("");
                     u_number.setText("");
                }
                 
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ID is already Exist");
                u_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.GREEN));// sarver error ,show message
            }
            finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                    if (stt != null) {
                        stt.close();
                    }
                } catch (SQLException sqlee) {
                    JOptionPane.showMessageDialog(null, sqlee.toString());
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       u_id.setText(""); u_pass.setText(""); a_type.setText(""); u_date.setText(""); nation.setText(""); u_nid.setText("");
        u_name.setText(""); u_number.setText(""); u_dob.setText(""); u_add.setText(""); 
        u_id.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_pass.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        a_type.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_date.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        nation.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_nid.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_name.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_number.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_add.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        u_dob.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.LIGHT_GRAY));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nation;
    private javax.swing.JTextField u_add;
    private javax.swing.JTextField u_date;
    private javax.swing.JTextField u_dob;
    private javax.swing.JTextField u_id;
    private javax.swing.JTextField u_name;
    private javax.swing.JTextField u_nid;
    private javax.swing.JTextField u_number;
    private javax.swing.JPasswordField u_pass;
    // End of variables declaration//GEN-END:variables
}
